# ================= НАСТРОЙКИ SOCKS5 ПРОКСИ =================
systemProp.socksProxyHost=127.0.0.1
systemProp.socksProxyPort=10808
systemProp.java.net.useSystemProxies=false

# ================= ВЕРСИИ МОДА И MINECRAFT =================
mod_version = 0.2.0
maven_group = com.mogdop.mod
archives_base_name = mogdops-mod
enabled_platforms = fabric,neoforge

minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.3
loader_version = 0.16.0

architectury_loom_version = 1.9-SNAPSHOT
architectury_version = 13.0.8

fabric_api_version = 0.102.0+1.21.1
neoforge_version = 21.1.65
modmenu_version = 11.0.4