plugins {
    id "dev.architectury.loom"
    id "architectury-plugin"
}

architectury {
    common("fabric", "neoforge")
}

loom {
    silentMojangMappingsLicense()
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings "net.fabricmc:yarn:${rootProject.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"

    // 100% локальные моды и библиотеки из libs/
    modImplementation fileTree(dir: "${rootProject.projectDir}/libs", include: ['*.jar'])
    annotationProcessor fileTree(dir: "${rootProject.projectDir}/libs", include: ['*.jar'])

    implementation "blue.endless:jankson:1.2.3"
    implementation "io.wispforest:endec:0.1.5"
    implementation "io.wispforest.endec:netty:0.1.2"
    implementation "io.wispforest.endec:gson:0.1.3"
    implementation "io.wispforest.endec:jankson:0.1.3"
}